notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

sudo: false

language: ruby

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t kallisto .
 - docker images | grep -c kallisto
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm kallisto kallisto version
